package main

import (
	_ "embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// athutilSource / athuiSource are the canonical runtime packages, embedded from
// the Athene source tree and stamped verbatim into every generated project so
// apps stay self-contained (no dependency on Athene being published).
//
//go:embed athutil/athutil.go
var athutilSource string

//go:embed athui/athui.go
var athuiSource string

// genLicenseHeader is prepended to machine-generated Go files. It carries the
// LGPL linking exception (see LICENSE.exception) so apps built with Athene can
// be distributed under any license.
const genLicenseHeader = `// SPDX-License-Identifier: LGPL-2.1-or-later
//
// This file was generated by Athene. As a special exception to the LGPL, you
// may combine it with your own independent modules and distribute the
// resulting executable under terms of your choice. See LICENSE.exception.

`

const gtkImport = "github.com/diamondburned/gotk4/pkg/gtk/v4"

// gotkVersion must match what the IDE itself resolved (see the root go.mod).
const gotkVersion = "v0.3.1"

// ---- handlers.go : the user's own code. athene only ever APPENDS stubs. ----

func handlersPath(dir string) string { return filepath.Join(dir, "handlers.go") }

// writeIfMissing writes content to path only if the file does not already
// exist, so regenerating a project never clobbers user-edited support files.
func writeIfMissing(path, content string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(path, []byte(content), 0644)
}

const handlersHeader = `package main

// This file holds YOUR event handlers.
// athene never rewrites your code here — when you double-click a widget it
// only appends a new empty stub if one does not already exist yet.
`

// ensureHandlerStub makes sure dir/handlers.go exists and contains a function
// named funcName, appending an empty stub if it is missing. Returns the full
// file contents afterwards.
func ensureHandlerStub(dir, funcName string) (string, error) {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	p := handlersPath(dir)
	data, err := os.ReadFile(p)
	if os.IsNotExist(err) {
		data = []byte(handlersHeader)
	} else if err != nil {
		return "", err
	}
	content := string(data)
	if funcName != "" && !strings.Contains(content, "func "+funcName+"(") {
		stub := fmt.Sprintf("\nfunc %s() {\n\t// TODO: your code here\n}\n", funcName)
		content += stub
	}
	if err := os.WriteFile(p, []byte(content), 0644); err != nil {
		return "", err
	}
	return content, nil
}

func readHandlers(dir string) string {
	data, err := os.ReadFile(handlersPath(dir))
	if err != nil {
		return handlersHeader
	}
	return string(data)
}

func writeHandlers(dir, content string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(handlersPath(dir), []byte(content), 0644)
}

// ---- app.gen.go : fully generated from the form. Overwritten every build. ----

func handlerName(w *Widget, event string) string {
	return "On" + w.ID + strings.Title(event)
}

func generateApp(f *Form) string {
	var b strings.Builder
	b.WriteString(genLicenseHeader)
	b.WriteString("// Code generated by athene. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n\t\"os\"\n\n\t\"" + gtkImport + "\"\n)\n\n")

	// Widgets are declared at package scope, RAD-style, so your event
	// handlers in handlers.go can reference any component by name, e.g.
	//   Label1.SetText("hello")
	b.WriteString("// Components — reach these from your handlers.go by name.\n")
	b.WriteString("var (\n")
	b.WriteString("\tMainWindow *gtk.ApplicationWindow\n")
	for _, w := range f.Widgets {
		if t := goType(w.Type); t != "" {
			b.WriteString(fmt.Sprintf("\t%s %s\n", w.ID, t))
		}
	}
	b.WriteString(")\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\tapp := gtk.NewApplication(\"com.athene.app\", 0)\n")
	b.WriteString("\tapp.ConnectActivate(func() { activate(app) })\n")
	b.WriteString("\tos.Exit(app.Run(os.Args))\n}\n\n")

	b.WriteString("func activate(app *gtk.Application) {\n")
	b.WriteString("\tMainWindow = gtk.NewApplicationWindow(app)\n")
	b.WriteString(fmt.Sprintf("\tMainWindow.SetTitle(%q)\n", f.Title))
	b.WriteString(fmt.Sprintf("\tMainWindow.SetDefaultSize(%d, %d)\n", f.Width, f.Height))
	b.WriteString("\tfixed := gtk.NewFixed()\n\n")

	for _, w := range f.Widgets {
		id := w.ID
		switch w.Type {
		case "Button":
			b.WriteString(fmt.Sprintf("\t%s = gtk.NewButtonWithLabel(%q)\n", id, w.Caption))
		case "Label":
			b.WriteString(fmt.Sprintf("\t%s = gtk.NewLabel(%q)\n", id, w.Caption))
		case "Entry":
			b.WriteString(fmt.Sprintf("\t%s = gtk.NewEntry()\n", id))
			if w.Caption != "" {
				b.WriteString(fmt.Sprintf("\t%s.SetText(%q)\n", id, w.Caption))
			}
		case "Box":
			b.WriteString(fmt.Sprintf("\t%s = gtk.NewFrame(%q)\n", id, w.Caption))
		default:
			continue
		}
		b.WriteString(fmt.Sprintf("\t%s.SetSizeRequest(%d, %d)\n", id, w.W, w.H))
		b.WriteString(fmt.Sprintf("\tfixed.Put(%s, %d, %d)\n", id, w.X, w.Y))
		if h, ok := w.Signals["clicked"]; ok && w.Type == "Button" {
			b.WriteString(fmt.Sprintf("\t%s.ConnectClicked(%s)\n", id, h))
		}
		b.WriteString("\n")
	}

	b.WriteString("\tMainWindow.SetChild(fixed)\n")
	b.WriteString("\tMainWindow.SetVisible(true)\n")
	b.WriteString("}\n")
	return b.String()
}

// goType maps a design widget type to the Go type of its generated component
// variable. Empty means the type is not emitted.
func goType(typ string) string {
	switch typ {
	case "Button":
		return "*gtk.Button"
	case "Label":
		return "*gtk.Label"
	case "Entry":
		return "*gtk.Entry"
	case "Box":
		return "*gtk.Frame"
	}
	return ""
}

func generateGoMod() string {
	return fmt.Sprintf("module atheneapp\n\ngo 1.24\n\nrequire %s %s\n",
		"github.com/diamondburned/gotk4/pkg", gotkVersion)
}

// generateMakefile emits a small Makefile driving the generated project.
func generateMakefile() string {
	return `# Makefile for an Athene-generated GTK4 application.
# Run 'make help' for the list of targets.

BIN := app

.PHONY: all build run tidy clean help

all: build

## build: compile the application to ./app
build:
	GOFLAGS=-mod=mod go build -o $(BIN) .

## run: build and launch the application
run: build
	./$(BIN)

## tidy: resolve dependencies and refresh go.sum
tidy:
	GOFLAGS=-mod=mod go mod tidy

## clean: remove the built binary
clean:
	rm -f $(BIN)

## help: list available targets
help:
	@grep -E '^## ' $(MAKEFILE_LIST) | sed 's/^## /  /'
`
}

// generateReadme emits a default README describing how to build the generated
// project on Debian- and Fedora-based Linux distributions.
func generateReadme(f *Form) string {
	title := f.Title
	if title == "" {
		title = "Athene application"
	}
	return fmt.Sprintf(`# %s

A native GTK4 application generated by **Athene**, the classic RAD form designer.

The app is a standard Go module (`+"`atheneapp`"+`) that compiles to a single native
executable. It uses [gotk4](https://github.com/diamondburned/gotk4) for GTK4
bindings, which link against the system GTK4 libraries via cgo.

## Files

- `+"`app.gen.go`"+` — generated from the form. **Do not edit**; it is overwritten on every build.
- `+"`handlers.go`"+` — your event handlers. Athene only ever appends new stubs here; your code is safe.
- `+"`athutil/`"+` — bundled helper package (overwritten every build). Import as `+"`atheneapp/athutil`"+` for forgiving Entry parsing, validation and number formatting, e.g. `+"`n := athutil.Atoi(entry.Text())`"+`.
- `+"`athui/`"+` — bundled message-box helpers (overwritten every build). Import as `+"`atheneapp/athui`"+`, e.g. `+"`athui.Info(MainWindow, \"Saved.\")`"+`.
- `+"`form.json`"+` — the form definition (if present).
- `+"`go.mod`"+` — the Go module definition.
- `+"`Makefile`"+` — convenience build targets.

## Prerequisites

You need the Go toolchain (1.24+), a C compiler, pkg-config, and the GTK4
development libraries.

### Debian / Ubuntu

    sudo apt update
    sudo apt install golang gcc pkg-config libgtk-4-dev libgirepository1.0-dev

### Fedora

    sudo dnf install golang gcc pkgconf-pkg-config gtk4-devel gobject-introspection-devel

## Build & run

    make build     # compile to ./app
    make run       # build, then launch
    make tidy      # resolve dependencies / refresh go.sum
    make clean     # remove the built binary

Or without make:

    GOFLAGS=-mod=mod go build -o app .
    ./app

> Note: the first build compiles the gotk4 cgo bindings and can take several
> minutes. Subsequent builds are cached and fast.

## License

**This application is yours to license however you like — including as a closed,
proprietary product.**

The Athene-generated code (`+"`app.gen.go`"+`) and the bundled `+"`athutil`"+` package are
covered by the LGPL v2.1 **with a linking exception** (the same approach the
Lazarus LCL/RTL uses). That exception lets you combine them with your own code
and distribute the result under any terms. Your only obligation is to honour the
LGPL for those files *themselves* — e.g. if you modify `+"`athutil.go`"+` and ship it,
share that change.

Dependencies keep their own licenses: [gotk4](https://github.com/diamondburned/gotk4)
is MPL-2.0, and GTK4 is LGPL, linked dynamically via your system libraries.
`, title)
}

// writeProject emits the generated + support files for the app project.
// It never touches handlers.go except to guarantee it exists.
func writeProject(dir string, f *Form) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "app.gen.go"), []byte(generateApp(f)), 0644); err != nil {
		return err
	}
	// The athutil/athui helper packages are machine-owned like app.gen.go: stamp
	// fresh copies every build so they stay in sync with the IDE. They are
	// internal packages of the generated module, imported as "<module>/athutil"
	// and "<module>/athui".
	if err := os.MkdirAll(filepath.Join(dir, "athutil"), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "athutil", "athutil.go"), []byte(athutilSource), 0644); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(dir, "athui"), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "athui", "athui.go"), []byte(athuiSource), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(generateGoMod()), 0644); err != nil {
		return err
	}
	// Makefile and README are user-facing conveniences: write them once, then
	// leave any edits alone on later builds.
	if err := writeIfMissing(filepath.Join(dir, "Makefile"), generateMakefile()); err != nil {
		return err
	}
	if err := writeIfMissing(filepath.Join(dir, "README.md"), generateReadme(f)); err != nil {
		return err
	}
	// Guarantee a stub exists for every wired signal so the generated code
	// always compiles. ensureHandlerStub is append-only: it never touches
	// handlers the user has already written.
	for _, w := range f.Widgets {
		for _, fn := range w.Signals {
			if _, err := ensureHandlerStub(dir, fn); err != nil {
				return err
			}
		}
	}
	if _, err := os.Stat(handlersPath(dir)); os.IsNotExist(err) {
		if err := os.WriteFile(handlersPath(dir), []byte(handlersHeader), 0644); err != nil {
			return err
		}
	}
	return nil
}

// buildApp resolves deps and compiles the project to dir/app. Returns combined
// tool output so the IDE can show it in its console.
func buildApp(dir string) (string, error) {
	var out strings.Builder
	steps := [][]string{
		{"go", "mod", "tidy"},
		{"go", "build", "-o", "app", "."},
	}
	for _, step := range steps {
		cmd := exec.Command(step[0], step[1:]...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
		o, err := cmd.CombinedOutput()
		out.Write(o)
		if err != nil {
			out.WriteString("\n" + strings.Join(step, " ") + " failed: " + err.Error() + "\n")
			return out.String(), err
		}
	}
	return out.String(), nil
}

// goModTidy resolves the project's dependencies (creating go.sum) so gopls and
// the compiler can find them. Best-effort; deps are already in the module cache.
func goModTidy(dir string) (string, error) {
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	out, err := cmd.CombinedOutput()
	return string(out), err
}

func runApp(dir string) error {
	cmd := exec.Command("./app")
	cmd.Dir = dir
	return cmd.Start()
}
